main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('shop/', include('shop.urls')),

]

shop/urls.py
from django.urls import path
from django.views.generic import TemplateView

from shop import views

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='shop'),
    path('cart/', views.cart_view, name='cart_view'),
    path('detail/<int:pk>/', views.ProductsDetailView.as_view(), name='shop_detail'),
    path('add-item-to-cart/<int:pk>', views.add_item_to_cart, name='add_item_to_cart'),
    path('delete_item/<int:pk>', views.CartDeleteItem.as_view(), name='cart_delete_item'),
    path('make-order/', views.make_order, name='make_order'),
]

shop/models.py
from _decimal import Decimal
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='product_name')
    code = models.CharField(max_length=255, verbose_name='product_code')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.CharField(max_length=255, blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.name} - {self.price}'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount}'

    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)




class Order(models.Model):
    STATUS_CART = '1_cart'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES = [
        (STATUS_CART, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # items = models.ManyToManyField(OrderItem, related_name='orders')
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART,
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None

        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0)
        return cart

    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount

    def make_order(self):
        items = self.orderitem_set.all()
        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpaid_orders(self.user)

    @staticmethod
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.product} - {self.price}'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)

@transaction.atomic()
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user, status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user, amount=-order.amount)

@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()

@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()

@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpaid_orders(user)

shop/forms.py
from django import forms

from shop.models import OrderItem


class AddQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, DeleteView

from shop.forms import AddQuantityForm
from shop.models import Product, Order, OrderItem


class ProductsListView(ListView):
    model = Product
    template_name = 'shop/shop.html'

class ProductsDetailView(DetailView):
    model = Product
    template_name = 'shop/shop-single.html'



@login_required(login_url=reverse_lazy('login'))
def add_item_to_cart(request, pk):
    if request.method == 'POST':
        quantity_form = AddQuantityForm(request.POST)
        if quantity_form.is_valid():
            quantity = quantity_form.cleaned_data['quantity']
            if quantity:
                cart = Order.get_cart(request.user)
                # product = Product.objects.get(pk=pk)
                product = get_object_or_404(Product, pk=pk)
                cart.orderitem_set.create(product=product,
                                          quantity=quantity,
                                          price=product.price)
                cart.save()
                return redirect('cart_view')
        else:
            pass
    return redirect('shop')



@login_required(login_url=reverse_lazy('login'))
def cart_view(request):
    cart = Order.get_cart(request.user)
    items = cart.orderitem_set.all()
    context = {
        'cart': cart,
        'items': items,
    }
    return render(request, 'shop/cart.html', context)




@method_decorator(login_required, name='dispatch')
class CartDeleteItem(DeleteView):
    model = OrderItem
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('cart_view')

    # Проверка доступа
    def get_queryset(self):
        qs = super().get_queryset()
        qs.filter(order__user=self.request.user)
        return qs

@login_required(login_url=reverse_lazy('login'))
def make_order(request):
    cart = Order.get_cart(request.user)
    cart.make_order()
    return redirect('shop')

templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Регистрация
{% endblock title %}

{% block container %}



{% for item in items %}
    <div class="row">
        <div class="col-12 col-md-1 item">
            &nbsp;&nbsp;&nbsp;{{ forloop.counter }}
        </div>
        <div class="col-12 col-md-4 item">
            {{ item.product }}
        </div>
        <div class="col-12 col-md-2 item">
            {{ item.quantity }}
        </div>
        <div class="col-12 col-md-2 item">
            {{ item.price }}
        </div>
        <div class="col-12 col-md-2 item">
            {{ item.amount }}
        </div>
        <div class="col-12 col-md-1 item">
        </div>

        </div>
<div class="col-12 col-md-1 item">
    <form method="post" action="{% url 'cart_delete_item' item.pk %}">
        {% csrf_token %}
        <button type="submit" style="color: blue"><u>delete</u></button>
    </form>
</div>

    </div>


{% endfor %}
<div class="row">
    <div class="col-12 col-md-1 item">
            {{ cart.amount }}
        </div>
    </div>


<a class="contactus-bar-btn f_right" href="{% url 'make_order' %}">
    Process to Payment
</a>


{% endblock container %}

templates/shop/shop-single.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Регистрация
{% endblock title %}

{% block container %}
    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>



    <!-- Open Content -->
    <section class="bg-light">
        <div class="container pb-5">
            <div class="row">
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{product.image_url}}" alt="Card image cap" id="product-detail">
                    </div>

<!--                    <div class="row">-->
<!--                        &lt;!&ndash;Start Controls&ndash;&gt;-->
<!--                        <div class="col-1 align-self-center">-->
<!--                            <a href="#multi-item-example" role="button" data-bs-slide="prev">-->
<!--                                <i class="text-dark fas fa-chevron-left"></i>-->
<!--                                <span class="sr-only">Previous</span>-->
<!--                            </a>-->
<!--                        </div>-->
<!--                        &lt;!&ndash;End Controls&ndash;&gt;-->
<!--                        &lt;!&ndash;Start Carousel Wrapper&ndash;&gt;-->
<!--                        <div id="multi-item-example" class="col-10 carousel slide carousel-multi-item" data-bs-ride="carousel">-->
<!--                            &lt;!&ndash;Start Slides&ndash;&gt;-->
<!--                            <div class="carousel-inner product-links-wap" role="listbox">-->

<!--                                &lt;!&ndash;First slide&ndash;&gt;-->
<!--                                <div class="carousel-item active">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="{{product.image_url}}" alt="Product Image 1">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_02.jpg" alt="Product Image 2">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_03.jpg" alt="Product Image 3">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                &lt;!&ndash;/.First slide&ndash;&gt;-->

<!--                                &lt;!&ndash;Second slide&ndash;&gt;-->
<!--                                <div class="carousel-item">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_04.jpg" alt="Product Image 4">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_05.jpg" alt="Product Image 5">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_06.jpg" alt="Product Image 6">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                &lt;!&ndash;/.Second slide&ndash;&gt;-->

<!--                                &lt;!&ndash;Third slide&ndash;&gt;-->
<!--                                <div class="carousel-item">-->
<!--                                    <div class="row">-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_07.jpg" alt="Product Image 7">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_08.jpg" alt="Product Image 8">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                        <div class="col-4">-->
<!--                                            <a href="#">-->
<!--                                                <img class="card-img img-fluid" src="assets/img/product_single_09.jpg" alt="Product Image 9">-->
<!--                                            </a>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                &lt;!&ndash;/.Third slide&ndash;&gt;-->
<!--                            </div>-->
<!--                            &lt;!&ndash;End Slides&ndash;&gt;-->
<!--                        </div>-->
<!--                        &lt;!&ndash;End Carousel Wrapper&ndash;&gt;-->
<!--                        &lt;!&ndash;Start Controls&ndash;&gt;-->
<!--                        <div class="col-1 align-self-center">-->
<!--                            <a href="#multi-item-example" role="button" data-bs-slide="next">-->
<!--                                <i class="text-dark fas fa-chevron-right"></i>-->
<!--                                <span class="sr-only">Next</span>-->
<!--                            </a>-->
<!--                        </div>-->
<!--                        &lt;!&ndash;End Controls&ndash;&gt;-->
<!--                    </div>-->

                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{ product.name}}</h1>
                            <p class="h3 py-2">{{ product.price|floatformat:0 }} РУБ.</p>

                            <h6>Описание:</h6>
                            <p>{{ product.note }}</p>

<!--                            <ul class="list-inline">-->
<!--                                <li class="list-inline-item">-->
<!--                                    <h6>Avaliable Color :</h6>-->
<!--                                </li>-->
<!--                                <li class="list-inline-item">-->
<!--                                    <p class="text-muted"><strong>White / Black</strong></p>-->
<!--                                </li>-->
<!--                            </ul>-->







                            <form action="{% url 'add_item_to_cart' product.pk %}" method="post">
                                <input type="hidden" name="product-title" value="Activewear">
                                <div class="row">
                                    <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item text-right">
                                                Quantity

                                                <input type="hidden" name="product-quanity" id="product-quanity" value="1" required id="id_quantity">
                                            </li>

										{% csrf_token %}
										<input type="number" name="quantity" value="1" min="1"
											   required id="id_quantity"/>

                                        </ul>
                                    </div>
<!--                                    <div class="col-auto">-->
<!--                                        <ul class="list-inline pb-3">-->
<!--                                            <li class="list-inline-item">Size :-->
<!--                                                <input type="hidden" name="product-size" id="product-size" value="S">-->
<!--                                            </li>-->
<!--                                            <li class="list-inline-item"><span class="btn btn-success btn-size">S</span></li>-->
<!--                                            <li class="list-inline-item"><span class="btn btn-success btn-size">M</span></li>-->
<!--                                            <li class="list-inline-item"><span class="btn btn-success btn-size">L</span></li>-->
<!--                                            <li class="list-inline-item"><span class="btn btn-success btn-size">XL</span></li>-->
<!--                                        </ul>-->
<!--                                    </div>-->

                                </div>
                                <div class="row pb-3">
                                    <div class="col d-grid">
                                        <button type="submit" class="btn btn-success btn-lg" name="submit" value="buy">Купить</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Content -->




{% endblock container %}